# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80d6b93dc5ea012f91467d65f8f66b20017040685363bfd0b17af50978a7b7e18d4025f1e9e867af760952ca34dde9a03d84ec2c68e440c38fdd832580e8116a

test:
  secret_key_base: 925084ee16a216c7191d586bd2d6a67922a900337ebccbe45004534e56ec5443b142f0e0b461bf06aac4d6902088e9e1a7d6a7732dad256665921a2ea23860ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
